### ISSUE TITLE
[Google][Search-Console] Owner verification and summary it.

### ISSUE THREAD

**Issue by HaJunMyoung** [HaJunMyoung/study_b#13]
# Required thing and Confirming
- [x] Adding "global site tag(gtag.js)" to <head> section of all of my blog's pages.
- [x] Confirm that is site tracking or not on Google Search Console.
  
# Testing
- [x] Search my blog on Google, and check about exposing.

**Comment by HaJunMyoung** [comment]
# almost Done
## Check lisk
- `Done` : gtag.js is successfully added at <head> section, in all of my blog's page
- `Done` : I confirmed that my site has been tracking by Google Search Console
- `Done` : Successfully linked google Analytics and Search Console
- `doing` : Confirming about exposing my site on Google.

## To-do
- [ ] summary about owner verification for google Search Console

**Comment by HaJunMyoung** [comment]
# all Done
