### ISSUE TITLE
@0915+@0916 Todo

### ISSUE THREAD

**Issue by HaJunMyoung** [HaJunMyoung/study_b#19]
# Modifying
## [Blog settings / Vuepress / Plugins / Smooth Scroll](https://hajunmyoung.github.io/study_b/src/vuepress/plugins.html#theme-config-%EB%B6%80%EB%93%9C%EB%9F%AC%EC%9A%B4-%EC%8A%A4%ED%81%AC%EB%A1%A4%EB%A7%81)
- [x] Delete the last paragraph. ("At the MS Edge, it doesn't work ~~")
    - Modify it because MS Edge support 'smooth scrolling' now.

## [Languages / HTML&CSS / introduction.html](https://hajunmyoung.github.io/study_b/src/languages/html_css/#html-css%EB%A5%BC-%EB%8B%A4%EB%A3%A8%EB%A9%B4%EC%84%9C)
- [x] Add this: " 'ML' of 'HTML' means 'Mark-up Languages' "

## [Search Console](https://hajunmyoung.github.io/study_b/src/google/search_console.html)
- [x] <gtag.js> example : file format change from .js to .html
- Search Console - 3.(적용)dev.html과 ssr.html을 이용한 비동기 추적 코드 삽입
  - [x] make a new blank line between "받으실 수 있을거에요." and "이제 이 추적코드를 dev.html에 다음과 같이 삽입하면"
  - [x] also at "페이지를 dev할 때마다, 모든 페이지 헤드 섹션에 해당 추적 코드가 삽입되어 있는 걸 볼 수 있어요." with "마찬가지로 ssr.html에 다음과 같이 삽입하면:"

**Comment by HaJunMyoung** [comment]
# all Done!
