### ISSUE TITLE
Todo: Contents of HTML

### ISSUE THREAD

**Issue by HaJunMyoung** [HaJunMyoung/study_b#20]
# first
- [x] Complete HTML/02_basicTags
- [x] Edit title of `02_basicTags.md` from "2.\~\~" to "02.\~\~"
- [x] Complete HTML/namedColors
- [x] Complete HTML/basicFonts

**Comment by HaJunMyoung** [comment]
- [Colors](https://www.w3schools.com/colors/colors_names.asp)
- [Fonts](https://delirussum.tistory.com/75)

**Comment by HaJunMyoung** [comment]
# all Done
