### ISSUE TITLE
Todo: @JS, studying 201030-001

### ISSUE THREAD

**Issue by HaJunMyoung** [HaJunMyoung/study_b#22]
# Study
**site [here](https://javascript.info)**  
1. An introduction
    - [ ] 1.1 An introduction to JavaScript
    - [ ] 1.2 Manuals and specifications
    - [ ] 1.3 Code editors
    - [ ] 1.4 Developer console
1. JavaScript Fundamentals
    - [ ] 2.1 Hello, world!
    - [ ] 2.2 Code structure
    - [ ] 2.3 The modern mode, "use strict"
    - [ ] 2.4 Variables
    - [ ] 2.5 Data types
    - [ ] 2.6 Interaction: alert, prompt, confirm
    - [ ] 2.7 Type Conversion
    - [ ] 2.8 Basic operators, maths
    - [ ] 2.9 Comparisons
    - [ ] 2.10 Conditional branching: if, '?'
    - [ ] 2.11 Logical operators
    - [ ] 2.12 Nullish coalescing operator '??'
    - [ ] 2.13 Loops: while and for
    - [ ] 2.14 The "switch" statement
    - [ ] 2.15 Functions
    - [ ] 2.16 Function expressions
    - [ ] 2.17 Arrow functions, the basics
    - [ ] 2.18 JavaScript specials

# for Study_blog
- [ ] Restructuring it.
- [ ] Summarize it.
