### ISSUE TITLE
July 3th, 2020 / to-do list

### ISSUE THREAD

**Issue by HaJunMyoung** [HaJunMyoung/study_b#4]
## Overall plan
- [x] Make introduction(README.md) of each categories  
- [x] Make correct sidebars 
- [x] Make correct nav-bars
  
## Detail plan : Contents of category 'Vuepress'
- [x] make 'Official guide in Korean' directory (h1 contents)
  - [x] modify directory of it for matching official guide's structure.
- [x] make Category : Vuepress blog making _ in 'src/Vuepress/' `canceled`
  - [x] fill the contents `canceled`

## Error modifying
- [x] version: ko-kr / root: Home / detail: '마지막 업데이트 시기/내용 확인하려면 여길 누르세요.' to '마지막 업데이트 시기와 내용을 확인하려면 여길 누르세요.'

**Comment by HaJunMyoung** [comment]
# all done
