### ISSUE TITLE
July 8th todo

### ISSUE THREAD

**Issue by HaJunMyoung** [HaJunMyoung/study_b#7]
# first, pull
- [x] I've modified at github. pull it!

## July 7th todo, first
- [x] after done

## July 8th todo
- [x] requirements for vuepress set-up
- [x] summarize [powerShell error](https://extbrain.tistory.com/118)
- [x] make Projects

## about requirements for vuepress set-up
- [x] [error](https://hajunmyoung.github.io/study_b/src/vuepress/ready_for_blog.html#%EC%A4%80%EB%B9%84%EB%AC%BC-3-clone-it): clone > code, modify it
- [x] [error](https://hajunmyoung.github.io/study_b/src/vuepress/ready_for_blog.html#node-%EC%99%80-yarn) '버젼(x.xx.x)가 > 버젼(x.xx.x)이'
- [x] separate "Node and yarn : introduction" and "yarn initializing"
- [x] add requirements : VS code
- [x] finish Requirements docu

**Comment by HaJunMyoung** [comment]
# all Done!
