### ISSUE TITLE
Todo list @0805

### ISSUE THREAD

**Issue by HaJunMyoung** [HaJunMyoung/study_b#9]
# Errors
## HTML/README.md
- [x] #html-α를-다루면서, paragraph 2, '그 구조도 *기본적이* 구조만 알면...' -> '그 구조도 *기본적인* 구조만 알면...'

# Let's Modify
## Arduino/README.md
- [x] #아두이노-메이킹의-기본 / merge paragraph 1 and 2 (cancel line changing)
- [x] #다양한-라이브러리/merge paragraph 1 and 2

**Comment by HaJunMyoung** [comment]
# All done
